<?php
if (!defined('ABSPATH')) { exit; }
class RC_Pages {
    private static $defs = null;
    public static function init(){ add_shortcode('reservechain_page',[__CLASS__,'shortcode']); add_shortcode('rc_waitlist',[__CLASS__,'waitlist_shortcode']); }
    public static function definitions(){ if(self::$defs===null) self::$defs=require RC_CORE_DIR.'includes/page-definitions.php'; return self::$defs; }
    public static function seed_pages(){
        $defs=self::definitions(); $home_id=0;
        foreach($defs as $d){
            $existing=get_page_by_path($d['slug']);
            $content='[reservechain_page key="'.esc_attr($d['key']).'"]';
            if($existing){ update_post_meta($existing->ID,'rc_page_key',$d['key']); if($d['key']==='home')$home_id=$existing->ID; continue; }
            $id=wp_insert_post(['post_title'=>$d['name'],'post_name'=>$d['slug'],'post_type'=>'page','post_status'=>'publish','post_content'=>$content]);
            if(!is_wp_error($id)){update_post_meta($id,'rc_page_key',$d['key']);if(in_array($d['key'],['participant-portal','redemption-portal','token-acquisition'],true))update_post_meta($id,'rc_noindex','1');if($d['key']==='home')$home_id=$id;}
        }
        if($home_id){update_option('show_on_front','page');update_option('page_on_front',$home_id);}
    }
    public static function get_def($key){ foreach(self::definitions() as $d)if($d['key']===$key)return $d; return null; }
    public static function shortcode($atts){ $a=shortcode_atts(['key'=>''],$atts); $d=self::get_def(sanitize_key($a['key'])); if(!$d)return '<div class="rc-notice">Unknown ReserveChain page definition.</div>';
        if($d['key']==='home')return self::render_home(); if($d['key']==='copper-powder')return self::render_asset('copper-powder'); if($d['key']==='nickel-wire')return self::render_asset('nickel-wire'); if($d['key']==='waitlist')return self::render_generic($d).self::waitlist_shortcode(); if(in_array($d['key'],['participant-portal','redemption-portal'],true))return self::render_portal($d); return self::render_generic($d);
    }
    private static function badge($txt,$cls=''){return '<span class="rc-badge '.esc_attr($cls).'">'.esc_html($txt).'</span>';}
    private static function button($slug,$label,$primary=false){$p=get_page_by_path($slug);$u=$p?get_permalink($p):home_url('/'.$slug.'/');return '<a class="rc-btn '.($primary?'rc-btn-primary':'rc-btn-secondary').'" href="'.esc_url($u).'">'.esc_html($label).'</a>';}
    public static function disclosure(){return '<div class="rc-notice"><strong>Mandatory pre-launch disclosure.</strong> '.esc_html(get_option('rc_mandatory_disclosure')).'</div>';}
    private static function render_home(){ $assets=RC_Registry::all_public(); ob_start(); ?>
        <section class="rc-hero"><div class="rc-container rc-hero-grid"><div><div class="rc-eyebrow">Institutional Real-World Asset Infrastructure</div><h1>Building the infrastructure for <span>tokenized industrial metals.</span></h1><p class="rc-lead">ReserveChain is developing an institutional platform intended to connect documented industrial-metal assets with digital identity, independent verification, custody, reserve reconciliation and future tokenization infrastructure.</p><div class="rc-actions"><?php echo self::button('waitlist','Join the Project Waitlist',true); echo self::button('how-it-works','Explore the Proposed Model'); echo self::button('industrial-metals','View Industrial Metal Programs'); ?></div><div class="rc-statusline"><span><?php echo esc_html(get_option('rc_corporate_status')); ?></span><span>Website mode: <?php echo esc_html(strtoupper(get_option('rc_mode','prelaunch'))); ?></span></div></div><div class="rc-hero-visual"><div class="rc-visual-core">RC</div><div class="rc-visual-label rc-vl1">Copper Powder<br><small>Evidence-led program</small></div><div class="rc-visual-label rc-vl2">Nickel Wire<br><small>0.025 mm program</small></div><div class="rc-visual-label rc-vl3">Digital Asset Passport<br><small>Identity + evidence</small></div><div class="rc-visual-label rc-vl4">Reserve Reconciliation<br><small>No live claim</small></div></div></div></section>
        <section class="rc-section"><div class="rc-container"><div class="rc-eyebrow">Initial Programs</div><h2>Physical assets first. Digital infrastructure second.</h2><div class="rc-grid rc-grid-2"><?php foreach($assets as $x)echo self::asset_card($x); ?></div></div></section>
        <section class="rc-section"><div class="rc-container"><div class="rc-eyebrow">Chain of Trust</div><h2>One coherent lifecycle from material to redemption.</h2><div class="rc-chain"><?php foreach(['Physical Asset','Verify','Value','Custody','Digital Asset Passport','Tokenize','Reconcile','Participate','Redeem'] as $i=>$s)echo '<div><b>'.($i+1).'</b><span>'.esc_html($s).'</span></div>'; ?></div></div></section>
        <section class="rc-section rc-section-tight"><div class="rc-narrow"><?php echo self::disclosure(); ?></div></section>
        <?php echo self::waitlist_shortcode(); return ob_get_clean(); }
    private static function asset_card($a){ $url=home_url('/'.sanitize_title($a['slug']).'/'); return '<article class="rc-card"><div class="rc-asset-visual '.esc_attr($a['material']==='Copper'?'copper':'nickel').'"></div>'.self::badge($a['verification_status']).'<h3>'.esc_html($a['name']).'</h3><div class="rc-specrow"><span>Purity <b>'.esc_html($a['purity']).'</b></span><span>'.($a['diameter']?'Diameter':'Lot').' <b>'.esc_html($a['diameter']?:$a['lot_id']).'</b></span></div><p>'.esc_html($a['evidence_note']).'</p><a class="rc-cardlink" href="'.esc_url($url).'">View asset program →</a></article>'; }
    private static function render_asset($slug){ $a=RC_Registry::by_slug($slug); if(!$a)return '<div class="rc-notice">Asset record unavailable.</div>'; ob_start(); ?>
        <section class="rc-pagehero"><div class="rc-container"><div class="rc-eyebrow">Initial Asset Program</div><h1><?php echo esc_html($a['name']); ?></h1><p><?php echo esc_html($a['evidence_note']); ?></p><div><?php echo self::badge('PRE-LAUNCH / EVIDENCE REVIEW'); echo ' '.self::badge('Tokenization: '.$a['tokenization_status'],'muted'); ?></div></div></section>
        <section class="rc-section"><div class="rc-container"><div class="rc-specgrid"><?php $specs=['Program ID'=>$a['program_id'],'Purity'=>$a['purity'],($a['diameter']?'Diameter':'Lot / Batch')=>($a['diameter']?:$a['lot_id']),'Laboratory'=>$a['laboratory'],'Certificate'=>$a['certificate_no'],'Certificate date'=>$a['certificate_date'],'Custody'=>$a['custody_status'],'Reserves'=>$a['reserve_status']]; foreach($specs as $k=>$v)echo '<div><span>'.esc_html($k).'</span><b>'.esc_html($v).'</b></div>'; ?></div></div></section>
        <section class="rc-section"><div class="rc-container rc-grid rc-grid-2"><div class="rc-card"><div class="rc-eyebrow">Evidence Architecture</div><h2>Laboratory evidence is a source record, not a reserve claim.</h2><p>The supplied Certificate of Analysis can support documented material specifications. Ownership, current inventory, custody, insurance, valuation, reserve eligibility and tokenization require separate approved records.</p></div><div class="rc-card"><div class="rc-eyebrow">Digital Asset Passport</div><h3><?php echo esc_html($a['passport_id']); ?></h3><?php echo self::badge('ILLUSTRATIVE / DEMO DATA','demo'); ?><table class="rc-table"><tr><th>Verification</th><td><?php echo esc_html($a['verification_status']); ?></td></tr><tr><th>Custody</th><td><?php echo esc_html($a['custody_status']); ?></td></tr><tr><th>Reserve</th><td><?php echo esc_html($a['reserve_status']); ?></td></tr><tr><th>Token</th><td><?php echo esc_html($a['tokenization_status']); ?></td></tr></table></div></div></section>
        <section class="rc-section rc-section-tight"><div class="rc-narrow"><?php echo self::disclosure(); ?></div></section>
        <?php return ob_get_clean(); }
    private static function render_generic($d){ ob_start(); ?><section class="rc-pagehero"><div class="rc-container"><div class="rc-eyebrow"><?php echo esc_html($d['category']); ?></div><h1><?php echo esc_html($d['title']); ?></h1><p><?php echo esc_html($d['summary']); ?></p><div class="rc-actions"><?php echo self::button('explore-assets','Explore Assets',true); echo self::button('contact','Contact ReserveChain'); ?></div></div></section><section class="rc-section"><div class="rc-container rc-grid rc-grid-3"><?php foreach($d['sections'] as $s): ?><article class="rc-card"><h3><?php echo esc_html($s['title']); ?></h3><p><?php echo esc_html($s['body']); ?></p></article><?php endforeach; ?></div></section><section class="rc-section rc-section-tight"><div class="rc-narrow"><?php echo self::disclosure(); ?></div></section><?php return ob_get_clean(); }
    private static function render_portal($d){ ob_start(); ?><section class="rc-pagehero"><div class="rc-container"><div class="rc-eyebrow">Portal Architecture</div><h1><?php echo esc_html($d['title']); ?></h1><p><?php echo esc_html($d['summary']); ?></p><?php echo self::badge('DEMO / INACTIVE TRANSACTION MODULES','demo'); ?></div></section><section class="rc-section"><div class="rc-container"><div class="rc-portal"><aside><b>Overview</b><span>Programs</span><span>Passports</span><span>Documents</span><span>Compliance</span><span>Transactions</span><span>Redemption</span><span>Security</span></aside><div><div class="rc-grid rc-grid-3"><div class="rc-card"><small>Compliance</small><h3>Not started</h3></div><div class="rc-card"><small>Token holdings</small><h3>Not active</h3></div><div class="rc-card"><small>Redemption</small><h3>Inactive</h3></div></div></div></div></div></section><?php return ob_get_clean(); }
    public static function waitlist_shortcode(){ ob_start(); ?><section class="rc-section"><div class="rc-container"><div class="rc-formcard"><div class="rc-eyebrow">Registration of Interest</div><h2>Join the project waitlist.</h2><p>No funds, payment details, wallet addresses or token reservations are collected.</p><form class="rc-waitlist-form"><input type="text" name="website" class="rc-hp" tabindex="-1" autocomplete="off"><div class="rc-formgrid"><label>First name<input name="first_name" required></label><label>Last name<input name="last_name" required></label><label>Email<input type="email" name="email" required></label><label>Country of residence<input name="country" required></label><label>Interest type<select name="participant_type"><option>Individual</option><option>Institution</option><option>Industrial buyer</option><option>Asset owner / originator</option><option>Enterprise</option></select></label><label>Material of interest<select name="material_interest"><option>Copper Powder</option><option>Nickel Wire</option><option>Both</option><option>Future asset programs</option></select></label></div><div class="rc-checks"><label><input type="checkbox" name="consent_updates" required> I consent to receive project-development communications.</label><label><input type="checkbox" name="privacy_ack" required> I acknowledge the privacy notice and pre-launch status.</label><label><input type="checkbox" name="no_offer_ack" required> I understand registration is not an investment, purchase, reservation or entitlement.</label></div><button type="submit" class="rc-btn rc-btn-primary">Register interest</button><div class="rc-formstatus" aria-live="polite"></div></form></div></div></section><?php return ob_get_clean(); }
}
